"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["#content[_ngcontent-%COMP%] {\r\n    padding: 15px;\r\n    min-height: 75vh;\r\n}\r\np[_ngcontent-%COMP%] {\r\n    word-wrap: break-word;\r\n}\r\nhr[_ngcontent-%COMP%] {\r\n    margin: 2.5px;\r\n}\r\n#noMargin[_ngcontent-%COMP%] {\r\n    margin:0px;\r\n}\r\n\r\n#noPadding[_ngcontent-%COMP%] {\r\n    padding:0px;\r\n}\r\n.testWithGreen[_ngcontent-%COMP%] {\r\n    background-color: green;\r\n}\r\n.testWithBlue[_ngcontent-%COMP%] {\r\n    background-color: blue;\r\n}\r\n.testWithRed[_ngcontent-%COMP%] {\r\n    background-color: red;\r\n}\r\n\r\n.fab[_ngcontent-%COMP%] {\r\n    position:float;\r\n    z-index:5;\r\n    right:0px;\r\n    bottom:0px;\r\n}\r\n\r\n#set-app-theme[_ngcontent-%COMP%] {\r\n    background-color: $be-app-theme-color;\r\n}", "$be-validation-error-color[_ngcontent-%COMP%]:   #F0506E[_ngcontent-%COMP%];\r\n$be-app-theme-color[_ngcontent-%COMP%]:   rgb(15[_ngcontent-%COMP%], 122[_ngcontent-%COMP%], 229)[_ngcontent-%COMP%];"];
exports.styles = styles;
//# sourceMappingURL=app.component.scss.shim.ngstyle.js.map