"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["footer[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    border-top: 1px solid #eee;\r\n    padding: 15px 0;\r\n    font-size: 20px;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=footer.component.scss.shim.ngstyle.js.map