"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["#sideMenuFreeScroll[_ngcontent-%COMP%] {\r\n    height: 120vh;\r\n    overflow-y: scroll;\r\n}\r\n\r\n#my-logo[_ngcontent-%COMP%] {\r\n    text-align:center;\r\n    font-family: 'Cinzel Decorative', cursive;\r\n    // font-family: 'Cinzel', serif;\r\n    font-weight: 700;\r\n    font-size: 20px;\r\n    color: white;\r\n    margin: 0px;\r\n}\r\nhr[_ngcontent-%COMP%] {\r\n    padding : 0px;\r\n    margin  : 0px\r\n}\r\n#pad-10[_ngcontent-%COMP%] {\r\n    padding: 10px 10px 10px 15px; \r\n}\r\n\r\n#sideMenuSubNav[_ngcontent-%COMP%] {\r\n    padding-left:40px;\r\n}\r\n\r\n#sideMenuFonts[_ngcontent-%COMP%] {\r\n    padding-left: 15px;\r\n    font-size: 16px;\r\n}\r\n#subSideMenuFonts[_ngcontent-%COMP%] {\r\n    font-size: 14px;\r\n}\r\n#independantScroll[_ngcontent-%COMP%] {\r\n    height: 110vh;\r\n    overflow-x: hidden;\r\n    overflow-y: scroll;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=sidebar.component.scss.shim.ngstyle.js.map