"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["#validation-error[_ngcontent-%COMP%] {\r\n    text-align:center;\r\n    color:white;\r\n    background-color: $be-validation-error-color;\r\n}\r\n\r\n.login-frame[_ngcontent-%COMP%] {\r\n    border: 2px solid $be-app-theme-color;\r\n    padding:30px;\r\n}\r\n\r\n.align-center[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n}", "$be-validation-error-color[_ngcontent-%COMP%]:   #F0506E[_ngcontent-%COMP%];\r\n$be-app-theme-color[_ngcontent-%COMP%]:   rgb(15[_ngcontent-%COMP%], 122[_ngcontent-%COMP%], 229)[_ngcontent-%COMP%];"];
exports.styles = styles;
//# sourceMappingURL=login.component.scss.shim.ngstyle.js.map