"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["i[_ngcontent-%COMP%] {\r\n    font-size:18px;\r\n    padding: 0px 5px 0px 5px;\r\n}\r\nul.pagination[_ngcontent-%COMP%] {\r\n    display: inline\r\n}\r\nul.pagination[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]{\r\n    display: inline\r\n}\r\nul.pagination[_ngcontent-%COMP%]   i[_ngcontent-%COMP%] {\r\n    font-size: 12px;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=presets-clients.component.scss.shim.ngstyle.js.map